title: Neurodesk
author: Neurodesk Team
logo: images/neurodesk_logo.svg
only_build_toc_files: true
execute:
  execute_notebooks: 'off'
  allow_errors: false
  timeout: 45000
  stderr_output: show
  run_in_temp: true
  execution_show_tb: true
  kernel_name: python3
repository:
  url: https://github.com/neurodesk/neurodeskedu
  path_to_book: books
  branch: main
html:
  favicon: images/neurodesk_logo.svg
  baseurl: https://neurodesk.org/edu
  repository_url: https://github.com/neurodesk/neurodeskedu
  use_issues_button: true
  use_repository_button: true
  use_download_button: true
  use_edit_page_button: true
sphinx:
  config:
    nb_code_prompt_hide: outputs
    nb_merge_streams: true
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    html_static_path:
    - _static
    html_js_files:
    - review-badge.js
    html_css_files:
    - review-badge.css
    html_theme_options:
      analytics:
        google_analytics_id: G-4Z9774J59Y
      repository_url: https://github.com/neurodesk/neurodeskedu
      path_to_docs: books
      repository_branch: main
      show_navbar_depth: 2
      navigation_depth: 3
      icon_links:
      - name: Return to neurodesk.org
        url: https://neurodesk.org
        icon: fa-solid fa-house
        type: fontawesome
      launch_buttons:
        jupyterhub_url: https://play-america.neurodesk.org
        notebook_interface: jupyterlab
        jupyterhub_servers:
        - text: Run in Australia
          url: https://play.neurodesk.cloud.edu.au
        - text: Run in Europe
          url: https://play-europe.neurodesk.org
        - text: Run in America
          url: https://play-america.neurodesk.org
        - text: Run in Global Server 1
          url: https://play-europe.neurodesk.org
        - text: Run in Global Server 2
          url: https://edu.neurodesk.org
  local_extensions:
    multiple_jupyterhub: _ext
    nd_review_meta: _ext
parse:
  myst_enable_extensions:
  - html_image
  - dollarmath
